services:
  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - "8080:8080"

  cachenode:
    build:
      context: .
      dockerfile: cachenode/Dockerfile
    environment:
      - GATEWAY_URL=http://gateway:8080
      - NODE_ADVERTISED_HOST=
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME=CacheTest
      - DB_USER=postgres
      - DB_PASSWORD=Miki.234
    depends_on:
      - gateway
