version: '3.8'

services:
  gateway:
    image: sehrawatmiki/dnc-gateway:latest
    ports:
      - "8080:8080"
    depends_on:
      - cachenode

  cachenode:
    image: sehrawatmiki/dnc-cachenode:latest
    environment:
      - GATEWAY_URL=http://gateway:8080
      - NODE_ADVERTISED_HOST=
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME=CacheTest
      - DB_USER=postgres
      - DB_PASSWORD=Miki.234
