spring.application.name=DNC

# 1. Connection Details
spring.datasource.url=jdbc:postgresql://localhost:5432/cache1
spring.datasource.username=postgres
# ^ Change to 'abyss_user' if you created one
spring.datasource.password=Miki.234
spring.jpa.hibernate.ddl-auto=create-drop