spring.application.name=dnc-gateway
server.port=8080

# Connection Details
spring.datasource.url=jdbc:postgresql://localhost:5432/cache1
spring.datasource.username=postgres
spring.datasource.password=Miki.234
spring.jpa.hibernate.ddl-auto=create-drop